name: moniepoint_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  android_id: ^0.4.0
  go_router: ^14.7.2
  auto_size_text: ^3.0.0
  device_info_plus: ^10.1.2
  device_preview: ^1.2.0
  dio: ^5.6.0
  dio_smart_retry: ^6.0.0
  file_picker: ^8.1.2
  firebase_app_installations: ^0.3.1+7
  firebase_core: ^3.6.0
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  supercharged: ^2.1.1
  mockito: ^5.4.0
  http: ^1.2.2
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decode: ^0.3.1
  loader_overlay: ^4.0.2+1
  logger: ^2.5.0
  permission_handler: ^11.0.1
  pretty_dio_logger: ^1.3.1
  printing: ^5.10.0
  rename: ^3.0.2
  sentry_flutter: ^8.12.0
  share: ^2.0.4
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.10
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.13.1
  equatable: ^2.0.7
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  dart_code_metrics_presets: ^2.13.0
  flutter_gen_runner: ^5.6.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1



flutter_icons:
  android: true
  ios: true
  Set "remove_alpha_ios: true"
  image_path: "assets/images/png/play_store_512.png"
  background_color: "#FFFFFF"
  

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/gif/
    - env/
    - env/dev.env
    - env/prod.env
    - env/uat.env

  fonts:
    - family: Sora
      fonts:
        - asset: fonts/sora/Sora-Regular.ttf
        - asset: fonts/sora/Sora-Bold.ttf
        - asset: fonts/sora/Sora-Medium.ttf
        - asset: fonts/sora/Sora-ExtraLight.ttf
        - asset: fonts/sora/Sora-ExtraBold.ttf
        - asset: fonts/sora/Sora-Thin.ttf
        - asset: fonts/sora/Sora-SemiBold.ttf
        - asset: fonts/sora/Sora-Light.ttf
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter_28pt-Regular.ttf
        - asset: fonts/inter/Inter_28pt-Bold.ttf
        - asset: fonts/inter/Inter_28pt-Medium.ttf
        - asset: fonts/inter/Inter_28pt-ExtraLight.ttf
        - asset: fonts/inter/Inter_28pt-ExtraBold.ttf
        - asset: fonts/inter/Inter_28pt-Thin.ttf
        - asset: fonts/inter/Inter_28pt-SemiBold.ttf
        - asset: fonts/inter/Inter_28pt-Light.ttf
    - family: DMSans
      fonts:
        - asset: fonts/dm-sans/DMSans-Regular.ttf
        - asset: fonts/dm-sans/DMSans-Bold.ttf
        - asset: fonts/dm-sans/DMSans-Medium.ttf
        - asset: fonts/dm-sans/DMSans-ExtraLight.ttf
        - asset: fonts/dm-sans/DMSans-ExtraBold.ttf
        - asset: fonts/dm-sans/DMSans-Thin.ttf
        - asset: fonts/dm-sans/DMSans-SemiBold.ttf
        - asset: fonts/dm-sans/DMSans-Light.ttf
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
        - asset: fonts/poppins/Poppins-Medium.ttf
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
        - asset: fonts/poppins/Poppins-ExtraBold.ttf
        - asset: fonts/poppins/Poppins-Thin.ttf
        - asset: fonts/poppins/Poppins-SemiBold.ttf
        - asset: fonts/poppins/Poppins-Light.ttf
    - family: Geist
      fonts:
        - asset: fonts/geist/Geist-Regular.otf
        - asset: fonts/geist/Geist-Bold.otf
        - asset: fonts/geist/Geist-Medium.otf
        - asset: fonts/geist/Geist-Thin.otf
        - asset: fonts/geist/Geist-SemiBold.otf
        - asset: fonts/geist/Geist-Light.otf
    - family: SpaceGrotesk
      fonts:
        - asset: fonts/space_grotesk/SpaceGrotesk-Regular.ttf
        - asset: fonts/space_grotesk/SpaceGrotesk-Bold.ttf
        - asset: fonts/space_grotesk/SpaceGrotesk-Medium.ttf
        - asset: fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
        - asset: fonts/space_grotesk/SpaceGrotesk-Light.ttf
    - family: Libre
      fonts:
        - asset: fonts/libre/LibreBaskerville-Regular.ttf
        - asset: fonts/libre/LibreBaskerville-Bold.ttf
        - asset: fonts/libre/LibreBaskerville-Italic.ttf
